SELECT E.EMP_NAME, D.DEPT_NAME, M.MANAGER_NAME, P.PROJECT_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
INNER JOIN  MANAGER M ON M.MANAGER_ID = E.MANAGER_ID
LEFT JOIN PROJECT P ON P.TEAM_MEMBER_ID = E.EMP_ID;


SELECT E.EMP_NAME, D.DEPT_NAME 
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;


CREATE TABLE FAMILY
(
	MEMBER_ID  VARCHAR(20),
	NAME VARCHAR(100),
	AGE INT,
	PARENT_ID VARCHAR(20)
);


INSERT INTO FAMILY
(MEMBER_ID, NAME, AGE, PARENT_ID)
VALUES  ('F1', 'DAVID', '4', 'F5'),
		('F2', 'CAROL', '10', 'F5'),
		('F3', 'MICHAEL', '12', 'F5'),
		('F4', 'JOHNSON', '36', ''),
		('F5', 'MARYAM', '40', 'F6'),
		('F6', 'STEWART', '70', '' ),
		('F7', 'ROHAN', '6', 'F4'),
		('F8', 'ASHA', '8', 'F4');



SELECT * FROM FAMILY
